# Generated by Django 4.2.11 on 2024-03-22 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_ordermodel_warehousemodel_orderdetailmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodtypemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodtypemodel',
            name='expiration_date',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=730), null=True),
        ),
        migrations.AlterField(
            model_name='goodtypemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
