# Generated by Django 4.2.11 on 2024-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_goodtypemodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
